### ISSUE TITLE
Some files seem to be missing

### ISSUE THREAD

**Issue by espressoelf** [Otakumouse/stormshade#2]
When I "installed" the latest release, StormShade didn't work. I couldn't change presets and all. Then I noticed some missing files:
```
dxgi.ini
FF14-1080.ini
FF14-1440.ini
FF14-4k.ini
FF14-Off.ini
```

I installed https://github.com/Otakumouse/stormshade/tree/47f93305f95732dabcea8a24d52a5f5438a7ae3c in the meantime.

**Comment by Lifell** [comment]
These aren't missing. They're left out on purpose.

The presets have been removed for now. You can still download them on the Stormshade Discord however. And dxgi.ini has been renamed to ReShade.ini. The renamed file makes it so that you won't ever need to rename it for reshade to recognize it. So, dxgi.dll, d3d11.dll, d3d9.dll, d3d10.dll will all work.

So, you not being able to change presets has nothing to do with any missing files.

**Comment by Wynadorn** [comment]
Ooh I see, then it's just the https://github.com/Otakumouse/stormshade/blob/master/README.md that needs updating

**Comment by Lifell** [comment]
Yeah, it's being updated/is ready pretty soon :]. Will be unleashed together with the new website as far as I know.
